### ISSUE TITLE
Add files to watch

### ISSUE THREAD

**Issue by DJ-Icebear** [statianzo/webpack-livereload-plugin#45]
How do I add more files to watch by this plugin? For example HTML files or files not touched by my webpack build?

**Comment by vs0uz4** [comment]
I'm having the same question, because I work with "Laravel" and would like it to update browsers when I needed the .php files as well.

**Comment by henrypenny** [comment]
This works for me:
https://github.com/pigcan/extra-watch-webpack-plugin
Add the plugin before `webpack-livereload-plugin` though.

**Comment by statianzo** [comment]
Thanks for the suggestion @henrypenny. Seems like a useful solution.

**Comment by farmerpaul** [comment]
@henrypenny: I tried the (https://github.com/pigcan/extra-watch-webpack-plugin)[extra-watch-webpack-plugin] as you suggested, placing it before `webpack-livereload-plugin`, in my Laravel Mix's webpack config settings, but changing the targeted PHP files still doesn't trigger a page reload. I still have to manually reload the browser to see those changes. Any ideas?

LiveReload works perfectly for CSS and JS, just not for PHP files.

Here's my `webpack.mix.js` file:
```js
const mix                     = require('laravel-mix');
const LiveReloadPlugin        = require('webpack-livereload-plugin');
const ExtraWatchWebpackPlugin = require('extra-watch-webpack-plugin');

require('@tinypixelco/laravel-mix-wp-blocks');

// Initialize Mix.
 mix
  .setPublicPath('./public')
  .webpackConfig({
    plugins: [
      new ExtraWatchWebpackPlugin({
        files: 'resources/views/**/*.php',
      }),
      new LiveReloadPlugin({
        useSourceHash   : true,
        appendScriptTag : true,
        port            : 4000,
      }),
    ],
  });

// Handle CSS.
mix
  .postCss('resources/styles/app.css', 'styles')
  .postCss('resources/styles/editor.css', 'styles')
  .options({
    processCssUrls: false,
    postCss: [
      require('postcss-import'),
      require('tailwindcss/nesting'),
      require('tailwindcss'),
      require('autoprefixer'),
    ],
  });

// Handle JS.
mix
  .js('resources/scripts/app.js', 'scripts')
  .js('resources/scripts/customizer.js', 'scripts')
  .blocks('resources/scripts/editor.js', 'scripts')
  .autoload({ jquery: ['$', 'window.jQuery'] })
  .extract();

// Copy assets.
mix
  .copyDirectory('resources/images', 'public/images')
  .copyDirectory('resources/fonts', 'public/fonts');

// Other settings.
mix
  .sourceMaps()
  .version();
```

**Comment by farmerpaul** [comment]
Turns out it started working as soon as I tried removing `useSourceHash: true`, and added `delay: 100` to the `LiveReloadPlugin` settings. I don't actually have a clue what's going on under the hood. It also turns out, I don't even need to use the `extra-watch-webpack-plugin` at all (maybe Laravel Mix is already set up to watch those PHP files).

I had earlier enabled `useSourceHash` to prevent the whole page from reloading when I only changed the CSS (which I found annoying), but doing that also disabled page reload on PHP file changes, for some unknown reason.

And if I didn't include `delay: 100` (or `delay: 500` or some positive integer), then it would only reload sporadically when the files changed. Using a number like 100 ms fixed this. Again, no idea why.

So for anyone who's interested, here's my revised, working `webpackConfig` section that now makes LiveReload work pretty well:

```js
mix
  .setPublicPath('./public')
  .webpackConfig({
    plugins: [
      new LiveReloadPlugin({
        appendScriptTag : true,
        port            : 4000,
        delay           : 100,
      }),
    ],
  });
```

**Comment by johnhooks** [comment]
This worked for me, I had to dig through the levels of abstraction the `webpack-livereload-plugin` adds to `livereload-js`. The option that need to be added to watch `php` files is, `ext: "js,css,php"`.

```js
mix
    .webpackConfig({
        plugins: [new LiveReloadPlugin({
            ignore: /(node_modules)|(vendor)/,
            // https://github.com/livereload/livereload-js/blob/master/src/options.js
            ext: "js,css,php"
        })],
```
